name: batchscoringdl
channels:
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.1.1
  - pip=10.0.1
  - python=3.6.7
  - prompt_toolkit=1.0.15
  - notebook=5.7.8
  - pip:
    - azure==4.0.0
    - azure-cli==2.0.66
    - azure-mgmt-storage==3.3.0
    - azure-mgmt-containerservice==5.3.0
    - azure-graphrbac==0.61.1
    - black==18.9b0
    - python-dotenv==0.9.1
    - scikit-image==0.15.0
    - matplotlib==3.0.3
    - torch==1.1.0
    - torchvision==0.3.0
